name: CI/CD Workflow

on: 
  push:
    branches:[main]
  pull_request:
    brancehs: [main]

jobs:
  buil-and-test:
    runs-on: ubunu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@4

      - name: Configurar Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        uses: npm install

      - name: Lint del codigo 
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm test 

